[package]
name = "libiot"
version = "0.1.0"
edition = "2024"

[dependencies]
heapless = "0.8.0"

[features]
default = []
std = []
async = []
defmt = []

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["alloc", "executor"] }
