[package]
name = "libiot"
version = "0.1.0"
edition = "2021"

[dependencies]

[features]
async = []
defmt = []

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["alloc", "executor"] }
